# TTP Analyzer Configuration File
# Supports configurable performance modes: fast, balanced, comprehensive

# ========================================
# PERFORMANCE MODE (NEW)
# ========================================
# Choose your preferred speed/accuracy tradeoff:
# - fast: Maximum speed, regex-only extraction (10-30x faster)
# - balanced: Good speed with enhanced accuracy (recommended)  
# - comprehensive: Maximum accuracy with full feature set
PERFORMANCE_MODE: "balanced"

# ========================================
# DIRECTORY STRUCTURE
# ========================================
GROUPS_DIR: "groups"
OUTPUT_DIR: "output"  
DATA_DIR: "data"
LOG_DIR: "logs"

# ========================================
# DATA FILES
# ========================================
ATTACK_DATA_FILE: "data/attack_data.json"
LOG_FILE: "logs/ttp_analyzer.log"

# ========================================
# EXTRACTION SETTINGS (Mode-Adaptive)
# ========================================
# Confidence threshold (adaptive based on mode):
# - fast: Uses higher threshold for speed
# - balanced: Uses this value 
# - comprehensive: Uses lower threshold for recall
MIN_CONFIDENCE_THRESHOLD: 0.6

# Heuristic extraction (only used in comprehensive mode)
ENABLE_HEURISTIC_EXTRACTION: true

# Maximum report size to process (MB)
MAX_REPORT_SIZE_MB: 25

# ========================================
# HTTP REQUEST SETTINGS
# ========================================
REQUEST_TIMEOUT: 15
RATE_LIMIT_DELAY: 0.5
MAX_RETRIES: 2
USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

# ========================================
# CONTENT PROCESSING (Mode-Adaptive)
# ========================================
# Minimum content length (adaptive):
# - fast: 50 chars
# - balanced: 100 chars  
# - comprehensive: 150 chars
MIN_CONTENT_LENGTH: 100

# ========================================
# LOGGING CONFIGURATION
# ========================================
LOG_LEVEL: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# ========================================
# VISUALIZATION SETTINGS
# ========================================
FIGURE_DPI: 150
FIGURE_SIZE: [12, 8]
COLOR_PALETTE: "husl"

# ========================================
# TIMELINE ANALYSIS
# ========================================
PHASE_WINDOW_DAYS: 30
ACTIVITY_GAP_THRESHOLD_DAYS: 30

# ========================================
# PERFORMANCE OPTIMIZATION
# ========================================
MAX_CONCURRENT_REQUESTS: 3
CACHE_REPORTS: false
CACHE_DURATION_HOURS: 0

# ========================================
# MODE-SPECIFIC OVERRIDES
# ========================================
# These settings override defaults based on performance mode

FAST_MODE_OVERRIDES:
  MIN_CONFIDENCE_THRESHOLD: 0.8
  MIN_CONTENT_LENGTH: 50
  REQUEST_TIMEOUT: 10
  ENABLE_HEURISTIC_EXTRACTION: false
  LOG_LEVEL: "WARNING"

BALANCED_MODE_OVERRIDES:
  MIN_CONFIDENCE_THRESHOLD: 0.6
  MIN_CONTENT_LENGTH: 100
  ENABLE_HEURISTIC_EXTRACTION: false  # Disabled for speed

COMPREHENSIVE_MODE_OVERRIDES:
  MIN_CONFIDENCE_THRESHOLD: 0.4
  MIN_CONTENT_LENGTH: 150
  REQUEST_TIMEOUT: 30
  ENABLE_HEURISTIC_EXTRACTION: true
  LOG_LEVEL: "DEBUG"

# ========================================
# VALIDATION SETTINGS (Mode-Adaptive)
# ========================================
VALIDATION_RULES:
  validate_technique_ids: true
  validate_dates: false        # Disabled in fast mode
  validate_sources: false      # Disabled in fast/balanced modes
  require_minimum_ttps: false

# ========================================
# EXPERIMENTAL FEATURES
# ========================================
EXPERIMENTAL:
  adaptive_confidence: true    # Adjust confidence based on content quality
  smart_content_filtering: true # Preserve TTP-relevant content
  batch_processing: false     # Enable for large-scale analysis
  performance_monitoring: true # Track timing metrics

# ========================================
# ERROR HANDLING
# ========================================
ERROR_HANDLING:
  continue_on_parse_error: true
  max_consecutive_failures: 5
  retry_failed_reports: false
  fail_fast_on_critical_errors: false

# ========================================
# PERFORMANCE TARGETS (for monitoring)
# ========================================
PERFORMANCE_TARGETS:
  # Fast mode targets
  fast_max_initialization_time_seconds: 0.5
  fast_max_report_parse_time_seconds: 0.5
  fast_max_ttp_extraction_time_seconds: 0.01
  fast_max_total_analysis_time_seconds: 30.0
  
  # Balanced mode targets  
  balanced_max_initialization_time_seconds: 1.0
  balanced_max_report_parse_time_seconds: 1.0
  balanced_max_ttp_extraction_time_seconds: 0.05
  balanced_max_total_analysis_time_seconds: 60.0
  
  # Comprehensive mode targets
  comprehensive_max_initialization_time_seconds: 2.0
  comprehensive_max_report_parse_time_seconds: 3.0
  comprehensive_max_ttp_extraction_time_seconds: 0.2
  comprehensive_max_total_analysis_time_seconds: 120.0

# ========================================
# DEBUG AND DEVELOPMENT
# ========================================
DEBUG_MODE: false
VERBOSE_TIMING: false
PROFILE_ENABLED: false

# ========================================
# MIGRATION SETTINGS
# ========================================
# For compatibility with existing configurations
LEGACY_COMPATIBILITY: true
WARN_ON_DEPRECATED_SETTINGS: true

# ========================================
# USAGE NOTES
# ========================================
# Performance Mode Recommendations:
#
# Use "fast" mode when:
# - Processing large numbers of reports (100+)
# - Time is critical
# - Reports contain explicit technique IDs (T1234, T1234.001)
# - Acceptable to miss some technique name matches
#
# Use "balanced" mode when:
# - General-purpose analysis (recommended default)
# - Good balance of speed and accuracy needed
# - Processing 10-50 reports
# - Want technique name matching but not heuristics
#
# Use "comprehensive" mode when:
# - Maximum accuracy is critical
# - Processing research-quality reports
# - Reports may use indirect technique references
# - Time is not a primary constraint
# - Need heuristic pattern matching
#
# Expected Performance (relative to original):
# - Fast: 10-30x faster initialization, 20-50x faster extraction
# - Balanced: 5-10x faster overall, similar accuracy to enhanced
# - Comprehensive: 2-3x faster, maximum accuracy